defaults:
  - global_conf: default
  - data_conf: default
  - model_conf: default
  - train_conf: default
  - _self_

name: Schrodinger

data_conf:
  initial_data_n: 10000
  boundary_data_n: 10000
  pde_data_n: 80000

global_conf:
  seed: 10

model_conf:
  dim:
    output_dim: 2
  layer:
    layer_n: 4
    layer_size: [64, 64, 64, 64]

problem_conf:
  dims: 2
  x_range: [-5, 5]
  t_range: [0., 1.57]
  initial_cond: 4 / (E**x + E**(-x))
  boundary_cond: periodic

train_conf:
  train_t_range: [ 0, 1.57 ]
#  eval_t_range: [ 0.9, 1.1 ]
#  test_t_range: [ 1.1, 1.57 ]
  pde_sampler: UniformSampler
  pde_reweighting: NoReWeighting
  reweighting_params:
    k_init: 2
    k_final: 2
    iter_n: ${train_conf.main_conf.max_steps}
  optim: adam
  optim_conf:
    lr: 1e-3
    betas: [ 0.9, 0.999 ]
    eps: 1e-8
    weight_decay: 0.0
    amsgrad: False
  sch: Identify
  sch_step:
    gamma: 0.1
    stage: 4
  main_conf:
    max_steps: 500000
    print_frequency: 1
    pde_batch_size: 80000
    initial_batch_size: 10000
    boundary_batch_size: 10000
    model_basic_save_name: ${name}
  sampler_conf:
    forward_batch_size: ${train_conf.main_conf.pde_batch_size}
    mesh_update_thres: 0.4
    rank_scale_factor: 1.0
    pow_scale_factor: 1.0
    addon_points: [ [ 0., -5. ], [ 0., 5. ], [ 0.9, -5.], [ 0.9, 5. ] ]
    seed_n: 1000
